name: go
on: [push]

jobs:

  build:
    name: lint, build & test

    runs-on: ubuntu-latest

    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: checkout
        uses: actions/checkout@v3

      - name: lint
        uses: golangci/golangci-lint-action@v3

      - name: build
        run: go build -race -v ./...

      - name: test
        run: go test -cover -race ./...
