name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Set up golint and staticcheck
      run: |
        go get -u honnef.co/go/tools/cmd/staticcheck
        go get -u golang.org/x/lint/golint

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Lint
      run: |
        test -z $(go fmt ./...)
        $(go env GOPATH)/bin/golint -set_exit_status
        $(go env GOPATH)/bin/staticcheck ./...

    - name: Build
      run: go build -race -v ./...

    - name: Test
      run: go build -cover -race ./...
